#!/bin/bash

set -e

modname=$1
currname="jclem\\/template-gofiber"

if [ -z "$modname" ]; then
    echo "Usage: $0 <modulename>"
    echo "  Slashes in modulename must be escaped."
    exit 1
fi

# Replace all instances of $currname with $modname in all contents.
find . -type f \
    -not -path "./.git/*" \
    -not -path "./tmp/*" \
    -not -path "./script/*" \
    -exec sed -i '' -e "s/$currname/$modname/g" {} \;
